FROM python:3.13-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . .
COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./

RUN apk add --no-cache gcc musl-dev linux-headers
RUN python -m venv .venv
RUN .venv/bin/pip3 install -r requirements.txt

ENV FLASK_APP microblog.py

#RUN chmod +x boot.sh
#RUN chown -R microblog:microblog ./

RUN <<-EOF
    chmod +x boot.sh
    chown -R microblog:microblog ./
EOF

USER microblog

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]